--- 
eureka: 
  client: 
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl: 
      defaultZone: "http:localhost:8761/eureka"
  intance: 
    perferIpAddress: true
server: 
  port: 8081
signing: 
  key: 345345fsdgsf5345
spring: 
  database: 
    driverClassName: com.mysql.jdbc.Driver
  datasource: 
    password: "BJzVyeGPHyh3z7CF68jkhe3X+BJzVyeGPHyh3z7CF68jkhe3X#34"
    testWhileIdle: "true"
    url: "jdbc:mysql://localhost:3306/itemsharingdatabase"
    username: amercado
    validation-query: "SELECT 1"
  jpa: 
    hibernate: 
      ddl-auto: update
    properties: 
      hibernate: 
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: "true"
